#######
# Compiled from splatoon/functions/weapons/splattershot.mcscript
# to .//splatoon/data/splatoon/functions/weapons/splattershot.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if entity @s[team=purple,scores={ink=10..}] run summon minecraft:armor_stand ~ ~ ~ {CustomName:"{\"text\":\"particle_purple\"}",Tags:["splattershot","projectile","purple"],NoGravity:1,Marker:1,Invisible:1}
execute if entity @s[team=purple,scores={ink=10..}] run scoreboard players set @e[type=armor_stand,name=particle_purple,limit=1,sort=nearest] duration 0
execute if entity @s[team=purple,scores={ink=10..}] anchored eyes run tp @e[type=armor_stand,name=particle_purple,limit=1,sort=nearest] ~ ~ ~ ~ ~
execute if entity @s[team=purple,scores={ink=10..}] anchored eyes run scoreboard players remove @s ink 10

execute if entity @s[team=cyan,scores={ink=10..}] run summon minecraft:armor_stand ~ ~ ~ {CustomName:"{\"text\":\"particle_cyan\"}",Tags:["splattershot","projectile","cyan"],NoGravity:1,Marker:1,Invisible:1}
execute if entity @s[team=cyan,scores={ink=10..}] run scoreboard players set @e[type=armor_stand,name=particle_purple,limit=1,sort=nearest] duration 0
execute if entity @s[team=cyan,scores={ink=10..}] anchored eyes run tp @e[type=armor_stand,name=particle_cyan,limit=1,sort=nearest] ~ ~ ~ ~ ~
execute if entity @s[team=cyan,scores={ink=10..}] anchored eyes run scoreboard players remove @s ink 10
