#######
# Compiled from splatoon/functions/weapons/weaponhandler.mcscript
# to .//splatoon/data/splatoon/functions/weapons/weaponhandler.mcfunction
#
# Generated by Minecraft Script for 1.13
######

execute as @a at @s store result score @s click run scoreboard players get @s click
execute as @a at @s if score @s click matches 1.. if score @s delay matches 10.. store result score @s delay run scoreboard players get @s delay
execute as @a at @s if score @s click matches 1.. if score @s delay matches 10.. if entity @s[nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{Unbreakable:1,display:{Name:"{\"text\":\"Splattershot\"}"},Damage:1}}}] run function splatoon:weapons/splattershot
execute as @a at @s if score @s click matches 1.. if score @s delay matches 10.. if entity @s[nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{Unbreakable:1,display:{Name:"{\"text\":\"Splattershot\"}"},Damage:1}}}] run scoreboard players set @s delay 0
execute as @a at @s if score @s click matches 1.. if score @s delay matches 30.. store result score @s delay run scoreboard players get @s delay
execute as @a at @s if score @s click matches 1.. if score @s delay matches 30.. if entity @s[nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{Unbreakable:1,display:{Name:"{\"text\":\"Sepiator\"}"},Damage:2}}}] run function splatoon:weapons/sepiator
execute as @a at @s if score @s click matches 1.. if score @s delay matches 30.. if entity @s[nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{Unbreakable:1,display:{Name:"{\"text\":\"Sepiator\"}"},Damage:2}}}] run scoreboard players set @s delay 0
execute as @a at @s if score @s click matches 1.. if score @s delay matches 30.. store result score @s delay run scoreboard players get @s delay
execute as @a at @s if score @s click matches 1.. if score @s delay matches 30.. if entity @s[nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{Unbreakable:1,display:{Name:"{\"text\":\"Slosher\"}"},Damage:3}}}] run function splatoon:weapons/slosher
execute as @a at @s if score @s click matches 1.. if score @s delay matches 30.. if entity @s[nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{Unbreakable:1,display:{Name:"{\"text\":\"Slosher\"}"},Damage:3}}}] run scoreboard players set @s delay 0
execute as @a at @s if score @s click matches 1.. if score @s delay matches 30.. store result score @s delay run scoreboard players get @s delay
execute as @a at @s if score @s click matches 1.. if score @s delay matches 30.. if entity @s[nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{Unbreakable:1,display:{Name:"{\"text\":\"Slosher\"}"},Damage:4}}}] run function splatoon:weapons/slosher
execute as @a at @s if score @s click matches 1.. if score @s delay matches 30.. if entity @s[nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{Unbreakable:1,display:{Name:"{\"text\":\"Slosher\"}"},Damage:4}}}] run scoreboard players set @s delay 0
execute as @a at @s if score @s click matches 1.. run scoreboard players set @s click 0
execute as @a at @s run scoreboard players add @s delay 1