#######
# Compiled from data/splatoon/functions/cheats.mcscript
# to .//splatoon/data/splatoon/functions/cheats.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @r[scores={infinityink=1..}] run tag @s remove tempink
execute as @r[scores={infinityink=1..}] unless entity @s[tag=triggerink] run tag @s add tempink
execute as @r[scores={infinityink=1..}] if entity @s[tag=tempink] run tag @s add triggerink
execute as @r[scores={infinityink=1..}] if entity @s[tag=tempink] run tellraw @s [{"text":"You've ","color":"reset"},{"text":"activated","color":"green"},{"text":" the cheat code ","color":"reset"},{"text":"infinityink","color":"gold"}]
execute as @r[scores={infinityink=1..}] unless entity @s[tag=tempink] run tag @s remove triggerink
execute as @r[scores={infinityink=1..}] unless entity @s[tag=tempink] run tellraw @s [{"text":"You've ","color":"reset"},{"text":"deactivated","color":"dark_red"},{"text":" the cheat code ","color":"reset"},{"text":"infinityink","color":"gold"},{"text":"!","color":"reset"}]
execute as @r[scores={infinityink=1..}] run scoreboard players set @a infinityink 0
execute as @r if entity @s[tag=triggerink] run scoreboard players set @s ink 250
execute as @r run scoreboard players enable @s infinityink