#######
# Compiled from data/splatoon/functions/executioner.mcscript
# to .//splatoon/data/splatoon/functions/executioner.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a at @s if entity @s[tag=invisibility] run effect give @s invisibility 1 0 true
execute as @a at @s unless entity @s[tag=invisibility] run effect clear @s invisibility
execute as @a at @s if entity @s[tag=speed] run scoreboard players add @s second 1
execute as @a at @s if entity @s[tag=speed] run effect give @s speed 1 20 true
execute as @a at @s if entity @s[tag=speed] as @s[scores={second=5..}] run function splatoon:second
execute as @a at @s if entity @s[tag=speed] as @s[scores={second=5..}] run scoreboard players set @a second 0
execute as @a at @s unless entity @s[tag=speed] run effect clear @s speed