#######
# Compiled from data/splatoon/functions/falling.mcscript
# to .//splatoon/data/splatoon/functions/falling.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @r[scores={sneak=1..}] at @s store result score @s sneak run scoreboard players get @s sneak
execute as @r[scores={sneak=1..}] at @s anchored feet if block ~ ~-0.1 ~ minecraft:iron_trapdoor[half=top] run tag @s add falling
execute as @r[scores={sneak=1..}] at @s anchored feet if block ~ ~-0.1 ~ minecraft:iron_trapdoor[half=top] run tp ~ ~-0.2 ~
execute as @r[scores={sneak=1..}] at @s anchored feet unless block ~ ~-0.1 ~ minecraft:iron_trapdoor[half=top] run tag @s remove falling
execute as @r[scores={sneak=1..}] at @s anchored eyes if block ^ ^ ^0.5 iron_trapdoor anchored feet run tp @s ~ ~ ~ ~ 0
execute as @r[scores={sneak=1..}] at @s anchored eyes if block ^ ^ ^0.5 iron_trapdoor anchored feet run tp @s ^ ^ ^1
execute as @r[scores={sneak=1..}] at @s anchored eyes if block ^ ^ ^0.5 iron_trapdoor run tag @s remove willbeteleported