#######
# Compiled from data/splatoon/functions/global.mcscript
# to .//splatoon/data/splatoon/functions/global.mcfunction
#
# Generated by Minecraft Script for 1.13
######


execute as @a at @s run tag @s[gamemode=!creative] add lobby
execute as @a at @s run tag @s[gamemode=creative] remove lobby
execute as @a at @s run tag @s remove dead
execute as @a at @s run tag @s remove invisibility
execute as @a at @s run tag @s remove speed
execute as @a at @s run tag @s remove falling
execute as @a at @s run tag @s remove hiding
execute as @a at @s run scoreboard players set counter counter 0
execute as @a at @s run tag @s add infinityink
execute as @a at @s run scoreboard players set @s start 0
execute as @a at @s run tag @s remove willbeteleported
tag @e[tag=mcscriptTags] remove hasStart