#######
# Compiled from data/splatoon/functions/hiding.mcscript
# to .//splatoon/data/splatoon/functions/hiding.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @r at @s store result score @s sneak run scoreboard players get @s sneak
execute as @r at @s unless entity @s[tag=lobby] if entity @s[team=purple] if block ~ ~-0.1 ~ #splatoon:purple_hide if score @s sneak matches 1.. run tag @s add hiding
execute as @r at @s unless entity @s[tag=lobby] if entity @s[team=purple] if block ~ ~-0.1 ~ #splatoon:purple_hide if score @s sneak matches 1.. run tag @s add invisibility
execute as @r at @s unless entity @s[tag=lobby] if entity @s[team=purple] if block ~ ~-0.1 ~ #splatoon:purple_hide if score @s sneak matches 1.. run tag @s add speed
execute as @r at @s unless entity @s[tag=lobby] if entity @s[team=purple] if block ~ ~-0.1 ~ #splatoon:cyan_hide run tag @s remove hiding
execute as @r at @s unless entity @s[tag=lobby] if entity @s[team=purple] if block ~ ~-0.1 ~ #splatoon:cyan_hide run effect give @s slowness 1 3 true
execute as @r at @s unless entity @s[tag=lobby] if entity @s[team=purple] if block ~ ~-0.1 ~ #splatoon:cyan_hide run tag @s remove speed
execute as @r at @s unless entity @s[tag=lobby] if entity @s[team=purple] unless block ~ ~-0.1 ~ #splatoon:purple_hide run tag @s remove hiding
execute as @r at @s unless entity @s[tag=lobby] if entity @s[team=purple] unless block ~ ~-0.1 ~ #splatoon:purple_hide run tag @s remove speed
execute as @r at @s unless entity @s[tag=lobby] if entity @s[team=cyan] if block ~ ~-0.1 ~ #splatoon:cyan_hide if score @s sneak matches 1.. run tag @s add hiding
execute as @r at @s unless entity @s[tag=lobby] if entity @s[team=cyan] if block ~ ~-0.1 ~ #splatoon:cyan_hide if score @s sneak matches 1.. run tag @s add speed
execute as @r at @s unless entity @s[tag=lobby] if entity @s[team=cyan] if block ~ ~-0.1 ~ #splatoon:purple_hide run tag @s remove hiding
execute as @r at @s unless entity @s[tag=lobby] if entity @s[team=cyan] if block ~ ~-0.1 ~ #splatoon:purple_hide run effect give @s slowness 1 3 true
execute as @r at @s unless entity @s[tag=lobby] if entity @s[team=cyan] if block ~ ~-0.1 ~ #splatoon:purple_hide run tag @s remove speed
execute as @r at @s unless entity @s[tag=lobby] if entity @s[team=cyan] unless block ~ ~-0.1 ~ #splatoon:cyan_hide run tag @s remove hiding
execute as @r at @s unless entity @s[tag=lobby] if entity @s[team=cyan] unless block ~ ~-0.1 ~ #splatoon:cyan_hide run tag @s remove speed
execute as @r at @s if score @s sneak matches 0 run tag @s remove hiding
execute as @r at @s if score @s sneak matches 0 run tag @s remove invisibility
execute as @r at @s if score @s sneak matches 0 run tag @s remove speed
execute as @r at @s if score @s sneak matches 1.. run tag @s add invisibility