#######
# Compiled from data/splatoon/functions/hphandler.mcscript
# to .//splatoon/data/splatoon/functions/hphandler.mcfunction
#
# Generated by Minecraft Script for 1.13
######

execute as @a[gamemode=!creative] at @s if block ~ ~-0.1 ~ #splatoon:killblocks run tag @s add dead
execute as @a[gamemode=!creative] at @s if block ~ ~-0.1 ~ #splatoon:alllist[waterlogged=true] run tag @s add dead
execute if entity @s[name=particle_cyan] run tag @a[distance=..0.5,team=purple,tag=!tempdamage,tag=!damage] add tempdamage
execute if entity @s[name=particle_cyan] run scoreboard players remove @a[tag=tempdamage,tag=!damage] hp 1
execute if entity @s[name=particle_cyan] run tag @a[tag=tempdamage] add damage
execute if entity @s[name=particle_cyan] run tag @a[tag=tempdamage] remove tempdamage
execute if entity @s[name=particle_cyan] run tag @a[distance=0.5..,tag=damage] remove damage

execute if entity @s[name=particle_purple] run tag @a[distance=..0.5,team=cyan,tag=!tempdamage,tag=!damage] add tempdamage
execute if entity @s[name=particle_purple] run scoreboard players remove @a[tag=tempdamage,tag=!damage] hp 1
execute if entity @s[name=particle_purple] run tag @a[tag=tempdamage] add damage
execute if entity @s[name=particle_purple] run tag @a[tag=tempdamage] remove tempdamage
execute if entity @s[name=particle_purple] run tag @a[distance=0.5..,tag=damage] remove damage

execute as @r[scores={hp=..0}] run scoreboard players set @s hp 0
execute as @r[scores={hp=..0}] run tag @s add dead
execute as @r[tag=dead] run scoreboard players set @s hp 6
execute as @r[team=cyan] if score @s hp = @s tempHp run replaceitem entity @s container.1 minecraft:command_block{CustomModelData:12}
execute as @r[team=cyan] if score @s hp = @s tempHp run scoreboard players set @s tempHp 6