#######
# Compiled from data/splatoon/functions/second.mcscript
# to .//splatoon/data/splatoon/functions/second.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players add @s ink 1