#######
# Compiled from data/splatoon/functions/squid.mcscript
# to .//splatoon/data/splatoon/functions/squid.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @r at @s run tag @e[type=armor_stand,name=squid,sort=random,limit=1,tag=!selected] add selected
execute as @a[scores={sneak=1..}] at @s if score @s id = @e[type=armor_stand,tag=selected,limit=1] id run tp @e[type=armor_stand,tag=selected,name=squid,limit=1] @s
execute as @a[scores={sneak=1..}] at @s if score @s id = @e[type=armor_stand,tag=selected,limit=1] id if entity @s[team=purple] if entity @s[tag=!hiding] unless entity @e[type=armor_stand,tag=selected,name=squid,limit=1,nbt={ArmorItems:[{},{},{},{id:"minecraft:stone_shovel",tag:{Damage:2,Unbreakable:1}}]}] run replaceitem entity @e[type=armor_stand,name=squid,tag=selected,limit=1] armor.head minecraft:stone_shovel{Damage:2,Unbreakable:1}
execute as @a[scores={sneak=1..}] at @s if score @s id = @e[type=armor_stand,tag=selected,limit=1] id if entity @s[team=purple] unless entity @s[tag=!hiding] run replaceitem entity @e[type=armor_stand,name=squid,tag=selected,limit=1] armor.head minecraft:air
execute as @a[scores={sneak=1..}] at @s if score @s id = @e[type=armor_stand,tag=selected,limit=1] id if entity @s[team=cyan] if entity @s[tag=!hiding] unless entity @e[type=armor_stand,tag=selected,name=squid,limit=1,nbt={ArmorItems:[{},{},{},{id:"minecraft:stone_shovel",tag:{Damage:1,Unbreakable:1}}]}] run replaceitem entity @e[type=armor_stand,name=squid,tag=selected,limit=1] armor.head minecraft:stone_shovel{Damage:1,Unbreakable:1}
execute as @a[scores={sneak=1..}] at @s if score @s id = @e[type=armor_stand,tag=selected,limit=1] id if entity @s[team=cyan] unless entity @s[tag=!hiding] run replaceitem entity @e[type=armor_stand,name=squid,tag=selected,limit=1] armor.head minecraft:air
execute as @a[scores={sneak=1..}] at @s if score @s id = @e[type=armor_stand,tag=selected,limit=1] id unless entity @s[team=purple] unless entity @s[team=cyan] if entity @s[tag=!hiding] unless entity @e[type=armor_stand,tag=selected,name=squid,limit=1,nbt={ArmorItems:[{},{},{},{id:"minecraft:stone_shovel",tag:{Damage:3,Unbreakable:1}}]}] run replaceitem entity @e[type=armor_stand,name=squid,tag=selected,limit=1] armor.head minecraft:stone_shovel{Damage:3,Unbreakable:1}
execute as @a[scores={sneak=1..}] at @s if score @s id = @e[type=armor_stand,tag=selected,limit=1] id unless entity @s[team=purple] unless entity @s[team=cyan] unless entity @s[tag=!hiding] run replaceitem entity @e[type=armor_stand,name=squid,tag=selected,limit=1] armor.head minecraft:air
execute as @a[scores={sneak=1..}] at @s run tag @e[type=armor_stand,name=squid,tag=selected] remove selected
execute as @r[scores={sneak=0}] at @s run tag @e[type=armor_stand,name=squid,sort=random,limit=1] add selected
execute as @r[scores={sneak=0}] at @s if score @s id = @e[type=armor_stand,tag=selected,limit=1] id run replaceitem entity @e[type=armor_stand,name=squid,tag=selected,limit=1] armor.head minecraft:air
execute as @r[scores={sneak=0}] at @s run tag @e[type=armor_stand,name=squid,tag=selected] remove selected