#######
# Compiled from data/splatoon/functions/start_game.mcscript
# to .//splatoon/data/splatoon/functions/start_game.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @r unless entity @e[tag=mcscriptTags,tag=hasStart] positioned -1 10 7 if block ~ ~ ~ minecraft:stone_button[powered=true] run tag @a remove lobby
execute as @r unless entity @e[tag=mcscriptTags,tag=hasStart] positioned -1 10 7 if block ~ ~ ~ minecraft:stone_button[powered=true] run scoreboard players add @p start 3600
execute as @r unless entity @e[tag=mcscriptTags,tag=hasStart] positioned -1 10 7 if block ~ ~ ~ minecraft:stone_button[powered=true] run tag @e[tag=mcscriptTags] add hasStart