#######
# Compiled from data/splatoon/functions/teamhandler.mcscript
# to .//splatoon/data/splatoon/functions/teamhandler.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a at @s if entity @e[type=area_effect_cloud,name="set cyan",distance=..2] if entity @s[team=!cyan] run tellraw @s [{"text":"Du bist nun in Team ","color":"reset"},{"text":"Cyan","color":"aqua"},{"text":"!","color":"reset"}]
execute as @a at @s if entity @e[type=area_effect_cloud,name="set cyan",distance=..2] if entity @s[team=!cyan] run team join cyan @s
execute as @a at @s if entity @e[type=area_effect_cloud,name="set purple",distance=..2] if entity @s[team=!purple] run tellraw @s [{"text":"Du bist nun in Team ","color":"reset"},{"text":"Purple","color":"dark_purple"},{"text":"!","color":"reset"}]
execute as @a at @s if entity @e[type=area_effect_cloud,name="set purple",distance=..2] if entity @s[team=!purple] run team join purple @s
execute as @a at @s store result score @s leave run scoreboard players get @s leave
execute as @a at @s if score @s leave matches 1.. run team leave @s
execute as @a at @s if score @s leave matches 1.. run scoreboard players set @s leave 0