#######
# Compiled from data/splatoon/functions/test.mcscript
# to .//splatoon/data/splatoon/functions/test.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players set @a test 0
execute if score @s test matches 0 run say hello

