#######
# Compiled from data/splatoon/functions/load.mcscript
# to .//splatoon/data/splatoon/functions/mcscript/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard objectives add counter dummy
scoreboard objectives add start dummy
execute unless entity @e[tag=mcscriptTags] at @p run summon armor_stand ~ ~ ~ {Tags:[mcscriptTags],Invisible:1,Invulnerable:1,NoGravity:1}

# Extended from splatoon/functions/developers/handledevtools.mcscript
# to splatoon/data/splatoon/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add devtools dummy

# Extended from data/splatoon/functions/hiding.mcscript
# to splatoon/data/splatoon/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add sneak dummy

# Extended from data/splatoon/functions/hphandler.mcscript
# to splatoon/data/splatoon/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add hp dummy

# Extended from data/splatoon/functions/load.mcscript
# to splatoon/data/splatoon/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add id dummy

execute unless entity @e[tag=mcscriptTags] at @p run summon armor_stand ~ ~ ~ {Tags:[mcscriptTags],Invisible:1,Invulnerable:1,NoGravity:1}
# Extended from data/splatoon/functions/main.mcscript
# to splatoon/data/splatoon/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add Age dummy

# Extended from data/splatoon/functions/teamhandler.mcscript
# to splatoon/data/splatoon/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add leave dummy

# Extended from splatoon/functions/weapons/sepiator.mcscript
# to splatoon/data/splatoon/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add duration dummy

# Extended from splatoon/functions/weapons/weaponhandler.mcscript
# to splatoon/data/splatoon/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add delay dummy
scoreboard objectives add click dummy

# Extended from data/splatoon/functions/test.mcscript
# to splatoon/data/splatoon/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add test dummy

# Extended from splatoon/functions/weapons/motion.mcscript
# to splatoon/data/splatoon/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add filledblocks dummy
