#######
# Compiled from splatoon/functions/developers/killbullets.mcscript
# to .//splatoon/data/splatoon/functions/developers/killbullets.mcfunction
#
# Generated by Minecraft Script for 1.13
######
kill @e[name="particle_purple",type=armor_stand]
kill @e[name="particle_cyan",type=armor_stand]