#######
# Compiled from splatoon/functions/weapons/weaponhandler.mcscript
# to .//splatoon/data/splatoon/functions/weapons/weapons/weaponhandler.mcfunction
#
# Generated by Minecraft Script for 1.13
######
# this file is generated based on a function specified in.//splatoon/data/splatoon/functions/weapons/weaponhandler.mcscript
execute as @a at @s run execute store result score @s click run scoreboard players get @s click
execute as @a at @s run execute if score @s click matches 1.. run execute if entity @s[nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{Unbreakable:1,display:{Name:"{\"text\":\"Gun\"}"}},Damage:1}}] run function splatoon:weapons/splattershot
execute as @a at @s run execute if score @s click matches 1.. run scoreboard players set @s click 0
execute as @a at @s run scoreboard players set @s sneak 0
