#######
# Compiled from data/splatoon/functions/main.mcscript
# to .//data/splatoon/functions/random/dropitemstodelete.mcfunction
#
# Generated by Minecraft Script for 1.13
######
# this file is generated based on a function specified in.//data/splatoon/functions/main.mcscript
execute as @e[type=item,distance=..2,scores={Age=..20}] run kill @s