#######
# Compiled from data/splatoon/functions/main.mcscript
# to .//splatoon/data/splatoon/functions/squid/playerids.mcfunction
#
# Generated by Minecraft Script for 1.13
######
# this file is generated based on a function specified in.//splatoon/data/splatoon/functions/main.mcscript
execute store result score @s id run scoreboard players get playerid id
scoreboard players add playerid id 1
tag @s add playerid
tag @s remove receiveID