#######
# Compiled from data/splatoon/functions/main.mcscript
# to .//splatoon/data/splatoon/functions/squid/summon.mcfunction
#
# Generated by Minecraft Script for 1.13
######
# this file is generated based on a function specified in.//splatoon/data/splatoon/functions/main.mcscript
summon armor_stand ~ ~ ~ {Invisible:1,CustomName:"{\"text\":\"squid\"}",NoGravity:1,Marker:1}
tag @s add summonedStand