#######
# Compiled from functions/developers/maps/beach.mcscript
# to .//splatoon/data/splatoon/functions/developers/maps/beach.mcfunction
#
# Generated by Minecraft Script for 1.13
######
clone 26 6 -85 53 20 -38 27 5 -206
tp @a[team=purple] 41 13 -161
tp @a[team=cyan] 40 13 -204