#######
# Compiled from functions/developers/maps/desert.mcscript
# to .//data/splatoon/functions/developers/maps/desert.mcfunction
#
# Generated by Minecraft Script for 1.13
######
clone -66 7 -84 -41 17 -39 28 6 -205
tp @a[team=purple] 49 10 -164
tp @a[team=cyan] 32 10 -201