#######
# Compiled from functions/developers/maps/factory.mcscript
# to .//splatoon/data/splatoon/functions/developers/maps/factory.mcfunction
#
# Generated by Minecraft Script for 1.13
######
clone -35 7 -84 -10 20 -39 28 6 -205
tp @a[team=purple] 49 10 -164
tp @a[team=cyan] 32 10 -201