#######
# Compiled from functions/developers/maps/forest.mcscript
# to .//splatoon/data/splatoon/functions/developers/maps/forest.mcfunction
#
# Generated by Minecraft Script for 1.13
######
clone -5 6 -85 22 17 -38 27 5 -206
tp @a[team=purple] 41 13 -161
tp @a[team=cyan] 40 13 -204