#######
# Compiled from functions/developers/maps/ice.mcscript
# to .//data/splatoon/functions/developers/maps/ice.mcfunction
#
# Generated by Minecraft Script for 1.13
######
clone 57 6 -85 84 20 -38 27 5 -206
tp @a[team=purple] 49 10 -164
tp @a[team=cyan] 32 10 -201