#######
# Compiled from functions/developers/maps/nether.mcscript
# to .//splatoon/data/splatoon/functions/developers/maps/nether.mcfunction
#
# Generated by Minecraft Script for 1.13
######
clone 88 6 -85 115 20 -38 27 5 -206
tp @a[team=purple] 49 10 -164
tp @a[team=cyan] 32 10 -201